{"commit_id": "ea9c217b47dbe834e9003ad91db76d02a8f6bfc4", "results": [{"type": "error", "test_name": "test_error (tests.test_app.TestPass)\nTest that our bencode raises when it recieves a malformed int", "reasons": ["\nTraceback (most recent call last):\n  File \"/Users/arnavpriyadarshi/Downloads/programming/python/example_ci/test_repos/sample_app_clone_runner/tests/test_app.py\", line 43, in test_error\n    raise ValueError(\"This should fail\")\nValueError: This should fail\n\n"]}, {"type": "fail", "test_name": "test_bad_math (tests.test_app.TestPass)\nTest that fails", "reasons": ["\nTraceback (most recent call last):\n  File \"/Users/arnavpriyadarshi/Downloads/programming/python/example_ci/test_repos/sample_app_clone_runner/tests/test_app.py\", line 36, in test_bad_math\n    self.assertEqual(1 + 1, 3)\nAssertionError: 2 != 3\n\n"]}, {"type": "fail", "test_name": "test_fail (tests.test_app.TestPass)\nTest that fails", "reasons": ["\nTraceback (most recent call last):\n  File \"/Users/arnavpriyadarshi/Downloads/programming/python/example_ci/test_repos/sample_app_clone_runner/tests/test_app.py\", line 32, in test_fail\n    self.assertTrue(False)\nAssertionError: False is not true\n\n"]}]}